---
global:
  name: consul
server:
  replicas: 1
  bootstrapExpect: 1
controller:
  enabled: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: false  # true will inject by default, otherwise requires annotation
  centralConfig:
    enabled: "true"